{{- $secrets := list "logfire-jwt-secret" "logfire-meta-write-token" "logfire-meta-frontend-token" "logfire-dex-client-secret" }}
{{- range $secret := $secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace $secret ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretVal := (get $secretData $secret ) | default (randAlphaNum 32 | b64enc) }}
  {{ $secret }}: {{ $secretVal | quote }}
{{- end }}
